### ISSUE TITLE
remark-torchlight is not a valid ES module?

### ISSUE THREAD

**Issue by kissu** [torchlight-api/remark-torchlight#4] opened 2022-05-22 23:13 UTC
Got this when tried to install the remark plugin to an Astro.js project, in an array of remark plugins, like the following
```js
remarkPlugins: [
  'remark-code-titles',
  ['rehype-autolink-headings', { behavior: 'prepend' }],
  ['remark-torchlight', {
    config: {
      token: 'sneaky-secret-token',
      theme: 'material-theme-palenight'
    }
  }]
],
```

<img width="646" alt="CleanShot 2022-05-23 at 01 10 20@2x" src="https://user-images.githubusercontent.com/5133074/169720009-eac7135f-c7f2-4dd1-b409-a803892147e2.png">

**Comment by cossssmin** [comment] 2022-05-30 08:10
Got the same trying to use it in Nuxt 2 with [Nuxt Content](https://content.nuxtjs.org/v1/getting-started/configuration/#markdown):

```js
// nuxt.config.js
export default {
  content: {
    markdown: {
      remarkPlugins: [
        ['remark-torchlight', {
          token: process.env.TORCHLIGHT_TOKEN,
          theme: 'github-light',
        }]
      ],
    }
  },
}
```

Result:

<img alt="image" src="https://user-images.githubusercontent.com/1656595/170947590-ca2f8582-8a69-4286-b51f-a628b0226610.png">

**Comment by jobyh** [comment] 2022-06-15 12:29
I believe this issue is a duplicate of #1 but to also capture here I'm also encountering the issue in NextJS (`swc` compiler)

**Comment by aarondfrancis** [comment] 2022-06-15 22:26
Let's chat over in #1

**Closed by aarondfrancis** 2022-06-15 22:26 UTC
